### ISSUE TITLE
ColorSet/ ColorConstants

### ISSUE THREAD

**Issue by miziaalmeida** [miziaalmeida/tmDB#7]
Faça um Enum nessa linha, e altera o nome desse enum ColorSet não faz muito sentido pro que você tá fazendo, talvez um bom nome seja `TokensColor`
https://github.com/miziaalmeida/tmDB/blob/1cea50c3e7266e6923cb445cfd43464ed4bdbf72/TheMovie/TheMovie/Common/ColorSet/ColorSet.swift#L13

Outra coisa, verifique se faz sentido ter esses dois caras, uma vez q tudo é referência de cor
https://github.com/miziaalmeida/tmDB/blob/1cea50c3e7266e6923cb445cfd43464ed4bdbf72/TheMovie/TheMovie/Common/Constants/ColorConstants.swift#L10

**Comment by jeiellima** [comment]
Feito!
