### ISSUE TITLE
Excluir comentários desnecessários

### ISSUE THREAD

**Issue by miziaalmeida** [miziaalmeida/tmDB#8]
Excluir comentários desnecessários no código
https://github.com/miziaalmeida/tmDB/blob/1cea50c3e7266e6923cb445cfd43464ed4bdbf72/TheMovie/TheMovie/Scenes/Login/LoginViewController.swift#L128

**Comment by miziaalmeida** [comment]
// TODO: REMOVER CÓDIGO UTILIZADO PARA PREVIEW POSTERIORMENTE (DATA)

**Comment by jeiellima** [comment]
Feito!
